create database test_foreign_key;

use test_foreign_key;

create table table1(id VARCHAR(10) primary key);
create table table2( id VARCHAR(10) primary key);
create table table3( id VARCHAR(10) primary key);
create table table4( id VARCHAR(10) primary key);
create table table5( id VARCHAR(10) primary key);
create table table6( id VARCHAR(10) primary key);
create table table7( id VARCHAR(10) primary key);
create table table8( id VARCHAR(10) primary key);
create table table9( id VARCHAR(10) primary key);
create table table10( id VARCHAR(10) primary key);
create table table11( id VARCHAR(10) primary key);
create table table12( id VARCHAR(10) primary key);
create table table13( id VARCHAR(10) primary key);
create table table14( id VARCHAR(10) primary key);
create table table15( id VARCHAR(10) primary key);
create table table16( id VARCHAR(10) primary key);
create table table17( id VARCHAR(10) primary key);
create table table18( id VARCHAR(10) primary key);
create table table19( id VARCHAR(10) primary key);
create table table20( id VARCHAR(10) primary key);
create table table21( id VARCHAR(10) primary key);
create table table22( id VARCHAR(10) primary key);
create table table23( id VARCHAR(10) primary key);
create table table24( id VARCHAR(10) primary key);
create table table25( id VARCHAR(10) primary key);
create table table26( id VARCHAR(10) primary key);
create table table27( id VARCHAR(10) primary key);
create table table28( id VARCHAR(10) primary key);
create table table29( id VARCHAR(10) primary key);
create table table30( id VARCHAR(10) primary key);
create table table31( id VARCHAR(10) primary key);
create table table32( id VARCHAR(10) primary key);
create table table33( id VARCHAR(10) primary key);
create table table34( id VARCHAR(10) primary key);
create table table35( id VARCHAR(10) primary key);
create table table36( id VARCHAR(10) primary key);
create table table37( id VARCHAR(10) primary key);
create table table38( id VARCHAR(10) primary key);
create table table39( id VARCHAR(10) primary key);
create table table40( id VARCHAR(10) primary key);
create table table41( id VARCHAR(10) primary key);
create table table42( id VARCHAR(10) primary key);
create table table43( id VARCHAR(10) primary key);
create table table44( id VARCHAR(10) primary key);
create table table45( id VARCHAR(10) primary key);
create table table46( id VARCHAR(10) primary key);
create table table47( id VARCHAR(10) primary key);
create table table48( id VARCHAR(10) primary key);
create table table49( id VARCHAR(10) primary key);
create table table50( id VARCHAR(10) primary key);
create table table51( id VARCHAR(10) primary key);
create table table52( id VARCHAR(10) primary key);
create table table53( id VARCHAR(10) primary key);
create table table54( id VARCHAR(10) primary key);
create table table55( id VARCHAR(10) primary key);
create table table56( id VARCHAR(10) primary key);
create table table57( id VARCHAR(10) primary key);
create table table58( id VARCHAR(10) primary key);
create table table59( id VARCHAR(10) primary key);
create table table60( id VARCHAR(10) primary key);
create table table61( id VARCHAR(10) primary key);
create table table62( id VARCHAR(10) primary key);
create table table63( id VARCHAR(10) primary key);
create table table64( id VARCHAR(10) primary key);
create table table65( id VARCHAR(10) primary key);
create table table66( id VARCHAR(10) primary key);
create table table67( id VARCHAR(10) primary key);
create table table68( id VARCHAR(10) primary key);
create table table69( id VARCHAR(10) primary key);
create table table70( id VARCHAR(10) primary key);


create table test_foreign_key_limit (id_1 VARCHAR(10), id_2 VARCHAR(10), id_3 VARCHAR(10), id_4 VARCHAR(10), id_5 VARCHAR(10), id_6 VARCHAR(10), id_7 VARCHAR(10), id_8 VARCHAR(10), id_9 VARCHAR(10), id_10 VARCHAR(10), id_11 VARCHAR(10), id_12 VARCHAR(10), id_13 VARCHAR(10), id_14 VARCHAR(10), id_15 VARCHAR(10), id_16 VARCHAR(10), id_17 VARCHAR(10), id_18 VARCHAR(10), id_19 VARCHAR(10), id_20 VARCHAR(10), id_21 VARCHAR(10), id_22 VARCHAR(10), id_23 VARCHAR(10), id_24 VARCHAR(10), id_25 VARCHAR(10), id_26 VARCHAR(10), id_27 VARCHAR(10), id_28 VARCHAR(10), id_29 VARCHAR(10), id_30 VARCHAR(10), id_31 VARCHAR(10), id_32 VARCHAR(10), id_33 VARCHAR(10), id_34 VARCHAR(10), id_35 VARCHAR(10), id_36 VARCHAR(10), id_37 VARCHAR(10), id_38 VARCHAR(10), id_39 VARCHAR(10), id_40 VARCHAR(10), id_41 VARCHAR(10), id_42 VARCHAR(10), id_43 VARCHAR(10), id_44 VARCHAR(10), id_45 VARCHAR(10), id_46 VARCHAR(10), id_47 VARCHAR(10), id_48 VARCHAR(10), id_49 VARCHAR(10), id_50 VARCHAR(10), id_51 VARCHAR(10), id_52 VARCHAR(10), id_53 VARCHAR(10), id_54 VARCHAR(10), id_55 VARCHAR(10), id_56 VARCHAR(10), id_57 VARCHAR(10), id_58 VARCHAR(10), id_59 VARCHAR(10), id_60 VARCHAR(10), id_61 VARCHAR(10), id_62 VARCHAR(10), id_63 VARCHAR(10), id_64 VARCHAR(10), id_65 VARCHAR(10), id_66 VARCHAR(10), id_67 VARCHAR(10), id_68 VARCHAR(10), id_69 VARCHAR(10), id_70 VARCHAR(10));

ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_1) REFERENCES table1(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_2) REFERENCES table2(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_3) REFERENCES table3(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_4) REFERENCES table4(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_5) REFERENCES table5(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_6) REFERENCES table6(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_7) REFERENCES table7(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_8) REFERENCES table8(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_9) REFERENCES table9(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_10) REFERENCES table10(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_11) REFERENCES table11(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_12) REFERENCES table12(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_13) REFERENCES table13(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_14) REFERENCES table14(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_15) REFERENCES table15(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_16) REFERENCES table16(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_17) REFERENCES table17(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_18) REFERENCES table18(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_19) REFERENCES table19(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_20) REFERENCES table20(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_21) REFERENCES table21(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_22) REFERENCES table22(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_23) REFERENCES table23(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_24) REFERENCES table24(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_25) REFERENCES table25(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_26) REFERENCES table26(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_27) REFERENCES table27(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_28) REFERENCES table28(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_29) REFERENCES table29(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_30) REFERENCES table30(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_31) REFERENCES table31(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_32) REFERENCES table32(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_33) REFERENCES table33(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_34) REFERENCES table34(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_35) REFERENCES table35(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_36) REFERENCES table36(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_37) REFERENCES table37(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_38) REFERENCES table38(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_39) REFERENCES table39(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_40) REFERENCES table40(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_41) REFERENCES table41(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_42) REFERENCES table42(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_43) REFERENCES table43(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_44) REFERENCES table44(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_45) REFERENCES table45(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_46) REFERENCES table46(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_47) REFERENCES table47(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_48) REFERENCES table48(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_49) REFERENCES table49(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_50) REFERENCES table50(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_51) REFERENCES table51(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_52) REFERENCES table52(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_53) REFERENCES table53(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_54) REFERENCES table54(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_55) REFERENCES table55(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_56) REFERENCES table56(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_57) REFERENCES table57(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_58) REFERENCES table58(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_59) REFERENCES table59(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_60) REFERENCES table60(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_61) REFERENCES table61(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_62) REFERENCES table62(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_63) REFERENCES table63(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_64) REFERENCES table64(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_65) REFERENCES table65(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_66) REFERENCES table66(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_67) REFERENCES table67(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_68) REFERENCES table68(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_69) REFERENCES table69(id);
ALTER TABLE test_foreign_key_limit ADD CONSTRAINT FOREIGN KEY(id_70) REFERENCES table70(id);